# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://timurey.github.io
title: Мастерская успеха
email: valentinataipova@gmail.com
author: Valentina Taipova
description: > # "партнерская система"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: vk
    url: https://vk.com/id3858151

# ------------------------------ #              
# Настройка адреса для рег.формы #
# например: exaple@gmail.com     #
# заполняем так:                 # 
# regform:                       #
#   - user: exaple               #
#     server: gmail.com          #
# количество пробелов важно!     #
# ------------------------------ #
regform:
  - user: valentinataipova
    server: gmail.com

# Color settings (hex-codes without the leading hash-tag)
register-button:
  primary-dark: '#000000'
  links: '#4ddba4'
  text: 'Заполняю анкету!'