# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Мастерская успеха
email: craz@list.ru
author: Valentina Taipova
description: > # "партнерская система"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/timurey/timurey.github.com
  - title: vk
    url: https://vk.com/id275006091

# ------------------------------ #              
# Настройка адреса для рег.формы #
# например: exaple@gmail.com     #
# заполняем так:                 # 
# regform:                       #
#   - user: exaple               #
#     server: gmail.com          #
# количество пробелов важно!     #
# ------------------------------ #
regform:
  - user: craz
    server: list.ru

# Color settings (hex-codes without the leading hash-tag)
register-button:
  primary-dark: '#000000'
  links: '#4ddba4'
  text: 'Присоединяюсь!'