# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://master-skaya.github.io
title: Валентина Таипова
email: valentinataipova@gmail.com
author: Valentina Taipova
description: > # "партнерская система"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: youtube
    url: https://www.youtube.com/channel/UCpTLLD1sJHEET1eIpJ7ne8g
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100009549590302
  - title: instagram
    url: https://www.instagram.com/valentina.taipova/
  - title: vk
    url: http://vk.com/id3858151
# ------------------------------ #              
# Настройка адреса для рег.формы #
# например: exaple@gmail.com     #
# заполняем так:                 # 
# regform:                       #
#   - user: exaple               #
#     server: gmail.com          #
# количество пробелов важно!     #
# ------------------------------ #
regform:
  - user: valentinataipova
    server: gmail.com

# Color settings (hex-codes without the leading hash-tag)
register-button:
  primary-dark: '#000000'
  links: '#4ddba4'
  text: 'Заполняю анкету!'

href-button:
  primary-dark: '#000000'
  links: '#4ddba4'
  href: "http://rabotavinet.com/?top=39"
  text: 'Подробности'